# Site settings
title: Knapen lab website
email: tknapen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website of the Knapen Computational Cognitive Neuroscience lab at the Vrije Universiteit Amsterdam.
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://tknapen.github.io # the base hostname & protocol for your site
twitter_username: tknapen
github_username:  tknapen
comments: true

plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  # hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts: 
    # css_class: highlight
    inline_theme: thankful_eyes
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# highlighter: rouge
# permalink: pretty

# Pagination
paginate: 4
paginate_path: "/blog/page:num/"

collections:
  science:
    output: true
    permalink: /science/:path/
  people:
    output: true
    permalink: /people/:path/
  resources:
    output: true
    permalink: /resources/:path/
  publications:
    output: true
    permalink: /publications/:path/


future: true